version: '3.9'

services:
  db:
    image: postgres:15
    container_name: studygroup_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: studygroup_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "2309:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
