spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:postgresql://localhost:2309/studygroup_db
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver

    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true

  jpa:
    properties:
      hibernate:
        generate_statistics: true
        cache:
          use_second_level_cache: true
          use_query_cache: false
          region:
            factory_class: org.infinispan.hibernate.cache.v62.InfinispanRegionFactory
            infinispan:
              cfg: infinispan-local.xml
    hibernate:
      ddl-auto: update

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: imports-bucket

app:
  cache:
    logging-enabled: true

server:
  port: 9090
